[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "eMolFrag2"
version = "2.0.0.2024.05.19"
dependencies = ["numpy", "rdkit", "colorlog", "networkx", "matplotlib"]
requires-python = ">=3.7"
authors = [
    { name = "Adam Bess", email = "bess@deepdrug.ai" },
    { name = "Chris Alvins", email = "calvin@deepdrug.ai" },
]
maintainers = [{ name = "Adam Bess", email = "bess@deepdrug.ai" }]
description = "A toolkit for fragmenting and analyzing molecular structures."
readme = "README.md"
keywords = ["chemistry", "molecule", "fragmentation", "bioinformatics"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Topic :: Scientific/Engineering :: Chemistry",
]

[project.optional-dependencies]
dev = ["pytest", "pytest-cov", "pyright"]

[project.urls]
Homepage = "https://deepdrug.ai"
Documentation = "https://readthedocs.org"
Repository = "https://github.com/deepdrugai/eMolFrag2"
"Bug Tracker" = "https://github.com/deepdrugai/eMolFrag2/issues"
Changelog = "https://github.com/deepdrugai/eMolFrag2/blob/master/CHANGELOG.md"

[tool.hatch.build.targets.wheel]
packages = ["src/eMolFrag"]
exclude = ["**/__pycache__", "**/*.pyc"]

[project.scripts]
emolfrag = "eMolFrag.eMolFrag:main"

[tool.hatch.envs.dev]
dependencies = ["pytest", "pytest-cov", "pyright"]
[tool.hatch.envs.dev.scripts]
types = "pyright --stats"
typesskip = "pyright --stats --skipunannotated"

[tool.pyright]
include = ["src/eMolFrag", "tests"]
exclude = ["src/eMolFrag/chopper/BRICS_custom.py"]

[tool.ruff]
line-length = 142

[tool.ruff.lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.
# select = ["E4", "E7", "E9", "F"]
# Enable flake8-bugbear (`B`) rules, in addition to the defaults.
# select = ["E4", "E7", "E9", "F", "B"]
# select = ["E", "F", "B"]

# Avoid enforcing f-string-missing-placeholders violations (`F541`), 
# flake8-self (SLF), flake8-blind-except (BLE001), flake8-errmsg (EM)
# flake8-boolean-trap (FBT), tryceratops 0s (TRY0), magic-value-comparison (PLR2004)
# flake8-print (T20) and Pep-8 Naming Rules (`N`).
ignore = ["N", "SLF", "F541", "BLE001", "EM", "TRY0", "FBT", "PLR2004", "T20"]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
# Avoid trying to fix flake8-bugbear (`B`) violations.
# unfixable = ["B"]

# Allow unused variables when underscore-prefixed.
# dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Ignore `E402` (import violations) in all `__init__.py` files, and in select subdirectories.
# [tool.ruff.lint.per-file-ignores]
# "__init__.py" = ["E402"]
# "**/{tests,docs,tools}/*" = ["E402"]

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

# Enable auto-formatting of code examples in docstrings. Markdown,
# reStructuredText code/literal blocks and doctests are all supported.
#
# This is currently disabled by default, but it is planned for this
# to be opt-out in the future.
docstring-code-format = false

# Set the line length limit used when formatting code snippets in
# docstrings.
#
# This only has an effect when the `docstring-code-format` setting is
# enabled.
docstring-code-line-length = "dynamic"
