[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "eMolFrag2"
version = "2.0.0.2024.05.19"
dependencies = ["rdkit", "colorlog", "networkx", "pandas", "matplotlib"]
requires-python = ">=3.8"
authors = [
    { name = "Pradyun Gedam", email = "pradyun@example.com" },
    { name = "Tzu-Ping Chung", email = "tzu-ping@example.com" },
]
maintainers = [{ name = "Brett Cannon", email = "brett@example.com" }]
description = "A toolkit for fragmenting and analyzing molecular structures."
readme = "README.md"
keywords = ["chemistry", "molecule", "fragmentation", "bioinformatics"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Topic :: Scientific/Engineering :: Chemistry",
    "License :: OSI Approved :: MIT License",
]

[project.optional-dependencies]
dev = ["pytest", "coverage"]

[project.urls]
Homepage = "https://example.com"
Documentation = "https://readthedocs.org"
Repository = "https://github.com/me/eMolFrag"
"Bug Tracker" = "https://github.com/me/eMolFrag/issues"
Changelog = "https://github.com/me/eMolFrag/blob/master/CHANGELOG.md"

[tool.hatch.build.targets.wheel]
packages = ["src/eMolFrag"]
# package-dir = { "eMolFrag2" = "src/eMolFrag" }
exclude = [
    "**/__pycache__",
    "**/*.pyc",
    "src/eMolFrag/output/UnitTestMol2.py",
    "src/eMolFrag/output/mols.1000.mol2",
    "src/eMolFrag/output/mols.1000.mol2.gz",
    "src/eMolFrag/output/mols.1000.mol2.gz-Zone.Identifier.txr",
]


# Uncomment the below lines if you have scripts or GUI scripts to include
[project.scripts]
emolfrag = "eMolFrag.eMolFrag:main"

# [project.gui-scripts]
# eMolFrag-gui = "src.eMolFrag:main_gui"

# [project.entry-points."eMolFrag.magical"]
# magic = "src.representation:Molecule"
